language: c
env:
  global:
  - PHARO_VERSION=70
addons:
  apt:
    packages:
    - libasound2:i386
    - libz1:i386
    - libbz2-1.0:i386
    - libssl1.0.0:i386
    - libfreetype6:i386

script:
 - "wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash"
 - "./scripts/install-packages.sh"
 - "zip -r bootstrapImage Pharo.image Pharo.changes Pharo7.0*.sources"
 
deploy:
  provider: releases
  api_key:
    secure: t04QBcT19JPoY/9hjUc3QTTPuH85onJOc0p3elD1XhXdfv6fNmsGp7kuhh83fTLizKtK5WoSKwBB1iXIWyBi3tJzxPAtKq8bVqZpauhWnJ7lwO+UGdMpq40uNuvIKZaMxeJ0e67Pk7/FfCfwa7UPYfWHrWvTu3JtaUKQb0X/YE/VY4HJvjeWkIpSu9fsPeRVRqHsFwVzfGSAw1qo1o5CBBujU3ih6m/zbj4SD1EIjIOxFL2mG3GVcri2Tm3jRaIhmxe6EtYvnHHR6LgldZEGSagQ68ApKiz9YxZpCBAGEfcZ4Fky/r655fNvPmMY6FOnJ3DBnCvRE5EB25SY2KDC4QkdDZfP5kBz6n7Qg2/vS+PVVNicdeI2amg39vAhGGq3hZZYZJ+OkZJifxTArRw51zDzy7U/sUi4r6cgu8uUqvdf2eAgKiwL3KC6XT9g0F4IiRsqx1N8wIJtroW+ml/hRFGuOEZ0DGdGLbm/zhw7tyCa48NZkptKleoP12I0H5iUYFOKGP4WCb4vl4+1Q6CSNvm/f4vHAIMNWmbnYRpzyXDdjAqWqdDaFdPYZi7t4WSktw+KWzdoUO5YhLZy1tXglsBAEGI8/pjNMyOG9Z+m/6fto4iB1IlPFXoVciH61V1LNLJTRtjM4Ar6MRPUw/CJlTRnANqjVR9yftBb0vXVV/Y=
  file: "bootstrapImage.zip"
  skip_cleanup: true
  on:
    repo: carolahp/PharoBootstrap
    tags: true
