language: c

env:
  global:
    - BOOTSTRAP_VERSION=6.0.60098
    - PHARO_VERSION=50
  matrix:
    - BOOTSTRAP_ARCH=32 BOOTSTRAP_DISTIRBUTION=default 
    - BOOTSTRAP_ARCH=64 BOOTSTRAP_DISTIRBUTION=default
    - BOOTSTRAP_ARCH=32 BOOTSTRAP_DISTIRBUTION=minimal 
    - BOOTSTRAP_ARCH=64 BOOTSTRAP_DISTIRBUTION=minimal


addons:
  apt:
    packages:
      - lib32asound2
      - lib32z1
      - lib32bz2-1.0
      - libssl1.0.0:i386
      - libfreetype6:i386

install: 
  - wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash
  - ./scripts/install-packages.sh

script:
  - ./scripts/run ${BOOTSTRAP_VERSION} ${BOOTSTRAP_ARCH} ${BOOTSTRAP_DISTIRBUTION}