language: c
env:
  global:
  - PHARO_VERSION=70
addons:
  apt:
    packages:
    - libasound2:i386
    - libz1:i386
    - libbz2-1.0:i386
    - libssl1.0.0:i386
    - libfreetype6:i386

script:
 - "wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash"
 - "./scripts/install-packages.sh"
 - "zip -r bootstrapImage Pharo.image Pharo.changes Pharo7.0*.sources"
 
deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: "bootstrapImage.zip"
  skip_cleanup: true
  on:
    repo: carolahp/PharoBootstrap
    tags: true
